[project]
name = "gateway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anyungu Wanyungu", email = "anyungucw@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.142.2",
    "fastmcp>=4.0.11",
    "httpx>=0.28.1",
    "pgvector>=0.5.0",
    "pydantic-settings>=2.15.0",
    "redis>=8.1.0",
    "sqlmodel>=0.0.47",
]

[project.scripts]
gateway = "gateway:main"

[tool.fastapi]
entrypoint = "gateway.main:app"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
